
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class NoteMap : Luban.BeanBase
{
    public NoteMap(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["music_name"].IsString) { throw new SerializationException(); }  MusicName = _buf["music_name"]; }
        { var __json0 = _buf["node_list"]; if(!__json0.IsArray) { throw new SerializationException(); } NodeList = new System.Collections.Generic.List<NoteModel>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { NoteModel __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = NoteModel.DeserializeNoteModel(__e0);  }  NodeList.Add(__v0); }   }
    }

    public static NoteMap DeserializeNoteMap(JSONNode _buf)
    {
        return new NoteMap(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 播放音乐名字
    /// </summary>
    public readonly string MusicName;
    /// <summary>
    /// 音符序列
    /// </summary>
    public readonly System.Collections.Generic.List<NoteModel> NodeList;
   
    public const int __ID__ = -501106710;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "musicName:" + MusicName + ","
        + "nodeList:" + Luban.StringUtil.CollectionToString(NodeList) + ","
        + "}";
    }
}

}

