
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial struct Note
{
    public Note(JSONNode _buf) 
    {
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
        { if(!_buf["track"].IsNumber) { throw new SerializationException(); }  Track = _buf["track"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["length"].IsNumber) { throw new SerializationException(); }  Length = _buf["length"]; }
        { if(!_buf["isReward"].IsNumber) { throw new SerializationException(); }  IsReward = _buf["isReward"]; }
    }

    public static Note DeserializeNote(JSONNode _buf)
    {
        return new Note(_buf);
    }

    public readonly float Time;
    public readonly int Track;
    public readonly float Speed;
    public readonly float Length;
    public readonly int IsReward;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "time:" + Time + ","
        + "track:" + Track + ","
        + "speed:" + Speed + ","
        + "length:" + Length + ","
        + "isReward:" + IsReward + ","
        + "}";
    }
}

}

