
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbHardSet TbHardSet {get; }
    public TbNoteMap TbNoteMap {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbHardSet = new TbHardSet(loader("tbhardset"));
        TbNoteMap = new TbNoteMap(loader("tbnotemap"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbHardSet.ResolveRef(this);
        TbNoteMap.ResolveRef(this);
    }
}

}
