
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHardSet
{
    private readonly System.Collections.Generic.Dictionary<int, HardSet> _dataMap;
    private readonly System.Collections.Generic.List<HardSet> _dataList;
    
    public TbHardSet(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HardSet>();
        _dataList = new System.Collections.Generic.List<HardSet>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HardSet _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HardSet.DeserializeHardSet(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HardSet> DataMap => _dataMap;
    public System.Collections.Generic.List<HardSet> DataList => _dataList;

    public HardSet GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HardSet Get(int key) => _dataMap[key];
    public HardSet this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

